# Generated by Django 5.0.1 on 2024-01-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0003_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='mail',
        ),
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
