# Generated by Django 5.0.1 on 2024-01-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0005_alter_subscription_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='email',
            new_name='u_email',
        ),
    ]
