# Generated by Django 5.0.1 on 2024-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0008_blog_post_alter_blog_category_blogcat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='blog_cat',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Kiwi', 'Kiwi'), ('Oranges', 'Oranges'), ('Strawberry', 'Strawberry')], default='unorganised', max_length=60),
        ),
    ]
